-- _config.yml --
```yaml
title: YouthSkills SA
description: Empowering South African Youth by bridging the skills gap and creating job opportunities.
baseurl: ""  # Leave blank if deploying to the root domain
url: "https://yourwebsite.com"  # Change to your actual domain
markdown: kramdown  # Allows Markdown usage
theme: minima  # Optional, choose a Jekyll theme or use custom styles
```




