title: YouthSkills SA
description: "Empowering South African youth through free skills training"
baseurl: ""
url: "https://yourusername.github.io" # Replace with your repo URL
theme: minima

plugins:
  - jekyll-seo-tag

# Optional social handles
twitter_username: YouthSkillsSA
facebook_username: YouthSkillsSA



